name: aoti-windows-test

on:
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string
        description: Name of the Windows build artifact to download
      cuda-version:
        required: true
        type: string
        description: CUDA version
      runner:
        required: true
        type: string
        description: Runner type to use for the test
      package-dir:
        required: false
        type: string
        default: D:\aoti_packages
        description: Directory where AOTI packages are stored
      s3-bucket:
        required: false
        type: string
        default: gha-artifacts
        description: S3 bucket for artifact storage
      timeout-minutes:
        required: false
        type: number
        default: 240
        description: Timeout in minutes
      win-torch-lib-dir:
        required: false
        type: string
        description: Windows torch libs directory path

jobs:
  test:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Enable git long paths and symlinks on Windows and disable fsmonitor daemon
        shell: bash
        run: |
          git config --global core.longpaths true
          git config --global core.symlinks true
          git config --global core.ignorecase false
          git config --global core.fsmonitor false

      - name: Setup SSH (Click me for login details)
        uses: pytorch/test-infra/.github/actions/setup-ssh@main
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
        with:
          no-sudo: true

      - name: Setup Windows
        uses: ./.github/actions/setup-win
        with:
          cuda-version: ${{ inputs.cuda-version }}

      - name: Download PyTorch Build Artifacts
        uses: seemethere/download-artifact-s3@v4
        with:
          name: ${{ inputs.build-artifact-name }}
          path: C:\${{ github.run_id }}\build-results

      - name: Download AOTI packages from S3
        uses: seemethere/download-artifact-s3@v4
        with:
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: ${{ github.repository }}/${{ github.run_id }}/artifacts/aoti-cross-compile
          path: ${{ inputs.package-dir }}

      - name: Verify packages
        shell: bash
        run: |
          echo "Build artifacts:"
          ls -la "C:/${{ github.run_id }}/build-results/" || echo "No build artifacts found"
          echo "AOTI packages:"
          ls -la "${{ inputs.package-dir }}/" || echo "No AOTI packages found"

      - name: Run Windows load tests
        shell: bash
        env:
          USE_CUDA: 1
        run: |
          # Run Windows load tests with downloaded packages
          python test/inductor/test_aoti_cross_compile_windows.py -k load --package-dir "${{ inputs.package-dir }}"
